apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-productivity-deploy
  labels:
    app: kubeacademy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeacademy
  template:
    metadata:
      labels:
        app: kubeacademy
    spec:
      containers:
      - name: developer-productivity-container
        image: lander2k2/developer-productivity:0.1

